### PR TITLE
Test framework for BridgeNet

### LINKED ISSUE #34: Develop a testing framework with integration properties specialized for BridgeNet
As BridgeNet gets more and more complex, the need for an automated testing framework becomes crucial. While I am aware of the fact that BridgeNet has an *okay* testing technique for testing *normal cases*, it becomes a nightmare to account for edge cases that require evalution for every output and input.

Additionally, using a pre-made testing framework like TestEZ or BoatTEST *(boatbomber's testing framework)* will not exactly fit the requirements for a testing framework that a networking library needs.

We need a framework that specifically allows us to:

1. Test everything from a single codebase on the client, and the communication infrastructure is managed by the Framework through a helper function.
2. Evaluate every output and input, accounting for edge cases
3. The ability to scale well by dividing multiple test cases into suites *(if it makes sense to do so)*.

I'm already willing to implement it and make a PR, however, I am looking to have a discussion about the design of the overall framework to avoid counter-productive patterns.

### PR DESCRIPTION
**Pull request by sinlerdev**
this closes #34.

Here is a list of things to be added:
- [x] assertion library
- [x] test dir reading
- [x] test outputing
- [x] errors reporting

### CODE REVIEW

**Comment by sinlerdev** [comment]
I am still wondering on how to approach test starting *(test dir reading)*, so I have come up with a few solutions. 

1#: 
```lua
tester.start({
 directories = {},
 context = THING
})
```
or 

2#: 
```lua
tester.start(directories, context)
```

**Comment by sinlerdev** [comment]
Getting some nice results from the output system I am developing!

Just to be clear, `!` is for instances passed to the directories' element in bootsrapper:start()'s configuration paramter, and `>` for normal instances that aren't test cases. Also, I haven't implemented the error part yet as I am planning on implementing it as an independent component from the output system *(similar to TestEZ's error reporting)* 

image

**Comment by sinlerdev** [comment]
Couldn't stop myself from doing this haha.
image

**Comment by sinlerdev** [comment]
I have finished the framework, however, if you don't mind, I am going to use this for a few projects of mine and/or will likely maintain it as a standalone project. 

Anyways, used this framework on a project I am developing and here's the results!
image

**Comment by sinlerdev** [comment]
I have finished the framework; it is ready for merging.

**Comment by ffrostflame** [comment]
Cool! I have zero problems with you using this for personal projects. It's open source, after all. Thanks a lot for the PR!

**Pull request merged**
