### PR TITLE
Optimisations for Pull Request #5

### PR DESCRIPTION
**Pull request by evanchan0819**
Same as Pull Request #5 but better performance.

### CODE REVIEW

**Comment by evanchan0819** [comment]
Also, can you add a new release please? @ffrostflame

**Comment by ffrostflame** [comment]
I can't add a new release yet, there's major unfinished changes. I'll do a new release when this is finished.
Working on roblox-ts port, global logging, and some other things.

Don't worry though there will be a new release today

**Comment by evanchan0819** [comment]
Can you approve this Pull Request then? It is better than my last fix.

**Comment by ffrostflame** [comment]
So sorry for the delay

**Comment by Baileyeatspizza** [comment]
Hey! any chance we can get this added back in?

image

for some reason, it was removed breaking my game 😖 . But adding it back in and my game works fine so maybe reconsider this change.

**Comment by evanchan0819** [comment]
What methods are you calling in the ClientBridge? It’s working fine for me.

**Comment by Baileyeatspizza** [comment]
I only used :Fire() it just only worked about 1/5 attempts :/

**Pull request merged**
